'''
389. Find the Difference

You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

'''
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        c = 0
        for cs in s: c ^= ord(cs) #ord is ASCII value
        for ct in t: c ^= ord(ct)
        return chr(c) #chr = convert ASCII into character

#less time

class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        ds,dt={}, {}
        for c in s:
            if c in ds: ds[c]+=1
            else: ds[c]=1
        for c in t:
            if c in dt: dt[c]+=1
            else: dt[c]=1
        for k in dt:
            if k not in ds or ds[k]!=dt[k]: return k

#less memory
class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        s_dict = {}
        for char in s:
            if char not in s_dict:
                s_dict[char] = 1
            else:
                s_dict[char] += 1
            
        for char in t:
            if char not in s_dict or s_dict[char] == 0:
                return char
            else:
                s_dict[char] -= 1